### PR TITLE
Add endpoint to get code system by OID/ID as FHIR

### LINKED ISSUE #35: Add endpoint to get a FHIR CodeSystem by OID
Get a specific code system by OID as FHIR, eg this endpoint on the existing FHIR API: https://phinvads.cdc.gov/baseStu3/CodeSystem/2.16.840.1.113883.12.1

To do this, import model from https://github.com/google/fhir/blob/master/go/proto/google/fhir/proto/r5/core/resources/code_system_go_proto/code_system.pb.go and serialize database model to it

### PR DESCRIPTION
**Pull request by nickclyde**
Resolves #35 

This adds an initial endpoint to get any code system by OID or ID, convert it to FHIR, and serve the response. Uses the protobuf generated types from https://github.com/google/fhir. 

Still a WIP - need to continue fleshing out the serializer, but you can get a half-baked FHIR response as is! 

Screenshot 2024-09-17 at 4 34 50 PM

### CODE REVIEW

**Review by katyasoup — COMMENTED** [review]
Love it! Wonder what your thoughts are re: separating things out into a new package by fhir version, e.g.:
```
app/
├─ fhir/
│  ├─ r5
│  │  ├─ CodeSystem.go <-- serializer, CodeSystem specific methods
│  │  ├─ ValueSet.go 
│  │  ├─ helpers.go <-- things like newString() that are applicable to all resources
│  │  ├─ etc.
│  ├─ r4
│  │  ├─ etc.
```

I like this approach ^ for keeping like with like and preventing too much sprawl; makes it a bit easier if/when we need to support multiple versions. And if we use versions for the package names, I find it makes the code clearer as well, e.g. `r5.newString()` vs `app.newString()` clues me in to the output without having to look at the function definition. 

Certainly not a blocker if we want to get things rolling quickly, but wanted to suggest it while it's still early days!

**Comment by nickclyde** [comment]
Yes, I think that is a great approach! Let's get some time scheduled to pair on it today.

**Comment by akintner** [comment]
I also like the idea of versioning from the get go for something like this.

**Comment by nickclyde** [comment]
Okay @katyasoup, reorganized as suggested, let me know if everything looks how you expected!

**Pull request closed without merging**
